on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-golang-app:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple

      - uses: docker://pandoc/latex:2.9
        if: ${{ steps.release.outputs.release_created }}
        with:
          args: --output=docs/Documentation.pdf docs/README.md

      - name: Upload Documentation to relase
        if: ${{ steps.release.outputs.release_created }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} docs/Documentation.pdf
