on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

env:
  APP_NAME: golang-release-example

jobs:
  release-golang-app:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: golang-release-example
